### ISSUE TITLE
How to bury/release a job - Not working

### ISSUE THREAD

**Issue by diegograssato** [JouwWeb/SlmQueueBeanstalkd#52]
### The class below does not exist, therefore the errors treatments do not work.
- SlmQueueBeanstalkd\Job\Exception

// Bury the job, with a priority of 10
throw new Exception\BuryableException(array('priority' => 10));

// Release the job, with a priority of 10 and delay of 5 seconds
throw new Exception\ReleasableException(array('priority' => 10, 'delay' => 5));

**Comment by ksvendsen** [comment]
@diegograssato  see https://github.com/juriansluiman/SlmQueueBeanstalkd/commit/dac19e39a0fe4e3364381c23e862a0d39786949f

The classes has been deprecated - you have to do it yourself in the job, by implementing `QueueAwareInterface` - see the post for example
